const CHECKOUT_PLANS = {
    p2: {
        id: 'p2',
        name: 'Pro Plan',
        kind: 'subscription',
        mode: 'subscription',
        priceId: 'price_1T4DptKpQn3RDJUCrhwtOx0u',
        tier: 'pro',
        weeklyPrivateQuota: 4,
    },
    p3: {
        id: 'p3',
        name: 'Premium Plan',
        kind: 'subscription',
        mode: 'subscription',
        priceId: 'price_1T4DrkKpQn3RDJUC7cPercNu',
        tier: 'vip',
        weeklyPrivateQuota: 10,
    },
    p4: {
        id: 'p4',
        name: 'Professional Business Plan',
        kind: 'subscription',
        mode: 'subscription',
        priceId: 'price_1T4DfJKpQn3RDJUC4ANefmpl',
        tier: 'professional',
        weeklyPrivateQuota: 0,
    },
    p5: {
        id: 'p5',
        name: 'Elite Partner Plan',
        kind: 'subscription',
        mode: 'subscription',
        priceId: 'price_1T4DlqKpQn3RDJUC6vrueW0n',
        tier: 'elite',
        weeklyPrivateQuota: 0,
    },
    elite: {
        id: 'elite',
        name: 'Paid Business',
        kind: 'subscription',
        mode: 'subscription',
        priceId: 'price_1T4DlqKpQn3RDJUC6vrueW0n',
        tier: 'elite',
        weeklyPrivateQuota: 0,
    },
    c1: {
        id: 'c1',
        name: 'Single Private Invitation',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1T4DyrKpQn3RDJUCN6ipD592',
        amount: 1,
    },
    c2: {
        id: 'c2',
        name: '3 Private Invitations',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1T4E1aKpQn3RDJUCMLLV7g4D',
        amount: 3,
    },
    c3: {
        id: 'c3',
        name: '5 Private Invitations',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1T4E1xKpQn3RDJUC6wYEr9I1',
        amount: 5,
    },
    c4: {
        id: 'c4',
        name: '10 Private Invitations',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1T4E3EKpQn3RDJUC97Rro1xj',
        amount: 10,
    },
    c5: {
        id: 'c5',
        name: '20 Private Invitations',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1T4E8AKpQn3RDJUCc3tJwnAI',
        amount: 20,
    },
    d1: {
        id: 'd1',
        name: '5 Dating Invitations',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1TDaNMKpQn3RDJUCWAJdI5YZ',
        amount: 5,
    },
    d2: {
        id: 'd2',
        name: '10 Dating Invitations',
        kind: 'private_pack',
        mode: 'payment',
        priceId: 'price_1TDaO5KpQn3RDJUC0vD1Afzj',
        amount: 10,
    },
    o1: {
        id: 'o1',
        name: '50 Hour Offer Slot',
        kind: 'offer_pack',
        mode: 'payment',
        priceId: 'price_1T5mIGKpQn3RDJUCMzhlyN6a',
        amount: 1,
    },
};

function getCheckoutPlan(planId) {
    return CHECKOUT_PLANS[String(planId || '').trim()] || null;
}

module.exports = {
    CHECKOUT_PLANS,
    getCheckoutPlan,
};
