storeFile=C:/Users/yaser/v1/dinebuddies/android/keystore/dinebuddies-upload.jks
storePassword=tDAUJzSJS88rYCBru5bnXk8g4I05KJvjv84cKY0wlB8C
keyAlias=dinebuddies
keyPassword=tDAUJzSJS88rYCBru5bnXk8g4I05KJvjv84cKY0wlB8C
